=== Chase22/CashBot/cashbot/src/main/resources/changelogs/changelog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.changelog.org/changelog" xmlns:tns="http://www.changelog.org/changelog" elementFormDefault="qualified">


    

    <complexType name="versionType">
    	<sequence minOccurs="1">
    		<element name="added" type="string" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    		<element name="removed" type="string" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    		<element name="deleted" type="string" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    		<element name="fixed" type="string" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="Version" use="required">
    		<simpleType>
    			<restriction base="string">
    				<pattern value="\d+.\d+.\d+"></pattern>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <element name="changelog" type="tns:changeLogType"></element>


    <complexType name="changeLogType">
    	<sequence>
    		<element name="Version" type="tns:versionType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
</schema>

=== Chase22/CashBot/cashbot/src/main/resources/changelogs/cashbot.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE changelog>
<changelog xmlns="http://www.changelog.org/changelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.changelog.org/changelog changelog.xsd">
	<Version Version="1.0.0">
		<added>first public release</added>
	</Version>
	<Version Version="1.1.0">
		<added>/changelog command to show the latest changelog</added>
		<added>/about command for information about the bot</added>
		<fixed>/setaccountto and /addtoaccount now show the currency name</fixed>
		<fixed>/openaccount now show the currency name</fixed>
	</Version>
</changelog>
