=== Chase22/CashBot/src/main/resources/changelog/changelog.xsd
<xs:schema elementFormDefault="qualified" targetNamespace="http://www.changelog.org/changelog" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="changelog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Version" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="description" minOccurs="0"/>
                            <xs:element type="xs:string" name="added" maxOccurs="unbounded" minOccurs="0"/>
                            <xs:element type="xs:string" name="fixed" maxOccurs="unbounded" minOccurs="0"/>
                            <xs:element type="xs:string" name="removed" maxOccurs="unbounded" minOccurs="0"/>
                            <xs:element type="xs:string" name="changed" maxOccurs="unbounded" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="Version" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Chase22/CashBot/src/main/resources/changelog/cashbot.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE changelog>
<changelog xmlns="http://www.changelog.org/changelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.changelog.org/changelog changelog.xsd">
	<Version Version="1.0.0">
		<description>first public release</description>
	</Version>
	<Version Version="1.1.0">
		<added>/changelog command to show the latest changelog</added>
		<added>/about command for information about the bot</added>
		<fixed>/setaccountto and /addtoaccount now show the currency name</fixed>
		<fixed>/openaccount now show the currency name</fixed>
		<fixed>transfers outside the integer limit caused log error</fixed>
	</Version>
    <Version Version="2.0.0">
        <description>Complete Rewrite of the bot</description>
    </Version>
</changelog>
